export const privacy = [
  {
    title: "",
    message: "Last updated: March 27, 2023This Privacy Policy describes Our policies and procedures on the collection,use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.We use Your Personal data to provide and improve the Service. By using theService, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the privacy policy"
  },
  {
    title: "Interpretation",
    message: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
  },
  {
    title: "Definitions",
    message: "For the purposes of this Privacy Policy: * Account means a unique account created for You to access our Service or parts of our Service. * Affiliate means an entity that controls, is controlled by or is under common control with a party, where control means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. * Application refers  findMyCard, the software program provided by the Company. * Company (referred to as either the Company, We, Us or Our in this Agreement) refers to findMyCard. * Country refers to: South Africa * Device means a device that can access the Service such as a computer, a cellphone or a digital tablet. * Personal Data is any information that relates to  identified or identifiable individual. * Service refers to the Application. * Service Provider mea any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. * Usage Da refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). * You means the individual accessing or using t Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  },
  {
    title: "Personal Data",
    message: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: * Email address * First name and last name * Phone number * Usage Data",
  },
  {
    title: "Usage Data",
    message: "Usage Data is collected automatically when using the Service.Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device. Information Collected while Using the Application ",
  },
  {
    title: "While using Our Application, in order to provide features of Our Application,We may collect, with Your prior permission:",
    message: "* Pictures and other information from your Device's camera and photo library We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.  You can enable or disable access to this information at any time, through Your Device settings.",
  },
  {
    title: "Retention of Your Personal Data",
    message: "The Company will retain Your Personal Data only for as long as is necessary   for the purposes set out in this Privacy Policy. We will retain and use Your   Personal Data to the extent necessary to comply with our legal obligations   (for example, if we are required to retain your data to comply with applicable   laws), resolve disputes, and enforce our legal agreements and policies.      The Company will also retain Usage Data for internal analysis purposes. Usage   Data is generally retained for a shorter period of time, except when this data   is used to strengthen the security or to improve the functionality of Our   Service, or We are legally obligated to retain this data for longer time   periods.",
  },
  {
    title: "Transfer of Your Personal Data",
    message: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.  Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.  The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
  },
  {
    title: "Delete Your Personal Data ",
    message: "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.  Our Service may give You the ability to delete certain information about You from within the Service.  You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.  Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
  },
];
